-- 📊 Schema de Tarefas para Supabase (Opcional)
-- Este arquivo contém a estrutura SQL para sincronizar tarefas com o banco de dados

-- ✅ Crie uma tabela "tasks" na sua dashboard Supabase
-- Vá para: SQL Editor → New Query → Cole este código

CREATE TABLE IF NOT EXISTS public.tasks (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL,
  nome TEXT NOT NULL,
  desc TEXT DEFAULT '',
  data DATE NOT NULL,
  hora TIME,
  prio TEXT NOT NULL CHECK (prio IN ('alta', 'media', 'baixa')),
  done BOOLEAN DEFAULT false,
  done_at BIGINT,
  recurrence TEXT DEFAULT 'none' CHECK (recurrence IN ('none', 'daily', 'weekly', 'monthly')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  
  CONSTRAINT tasks_user_id_fk FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- 🔒 Row Level Security - cada usuário vê só suas tarefas
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- 📖 SELECT Policy - Usuários veem suas próprias tarefas
CREATE POLICY "Users can select their own tasks" ON public.tasks
  FOR SELECT
  USING (auth.uid() = user_id);

-- ➕ INSERT Policy - Usuários criam tarefas para si mesmos
CREATE POLICY "Users can insert their own tasks" ON public.tasks
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- ✏️ UPDATE Policy - Usuários editam suas próprias tarefas
CREATE POLICY "Users can update their own tasks" ON public.tasks
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- 🗑️ DELETE Policy - Usuários deletam suas próprias tarefas
CREATE POLICY "Users can delete their own tasks" ON public.tasks
  FOR DELETE
  USING (auth.uid() = user_id);

-- 📇 Índices para performance
CREATE INDEX idx_tasks_user_id ON public.tasks(user_id);
CREATE INDEX idx_tasks_data ON public.tasks(data);
CREATE INDEX idx_tasks_done ON public.tasks(done);

-- 🔄 Auto-update de updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = TIMEZONE('utc'::text, NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_tasks_updated_at BEFORE UPDATE ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 📝 Exemplo de dados (comentado)
/*
INSERT INTO public.tasks 
  (user_id, nome, desc, data, hora, prio, done, recurrence)
VALUES 
  ('seu-user-id-aqui', 'Exemplo de tarefa', 'Descrição', '2024-12-25', '10:00', 'alta', false, 'none');
*/
